- hosts: webserver
  tasks:
    - name: "Installing Web Server (HTTPD)"
      package:
        name: "httpd"
        state: present
    
    - name: "Installing PHP package"
      package:
        name: "php"
        state: present

    - name: "Deploying (copying) Web Page"
      copy:
        src: "index.php"
        dest: "/var/www/html"

    - name: "Starting Web Server now"
      service:
        name: "httpd"
        state: started
        enabled: true